# GitHub Sponsors funding file
# Simple sponsor button activation

github: [melihcanndemir]
patreon: # Add if you have Patreon
open_collective: # Add if you have Open Collective
ko_fi: # Add if you have Ko-fi
tidelift: # Add if applicable
community_bridge: # Add if applicable
liberapay: # Add if you have Liberapay
issuehunt: # Add if you have IssueHunt
otechie: # Add if you have Otechie
lfx_crowdfunding: # Add if applicable
custom: # Add custom sponsor links if needed
  # - "https://example.com"
